# ===============================
# Banco de Dados MySQL
# ===============================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: ticket_tool_db
            - name: MYSQL_USER
              value: ticketuser
            - name: MYSQL_PASSWORD
              value: ticketpass
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP

# ===============================
# API Backend (AdonisJS)
# ===============================
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-tool-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ticket-tool-api
  template:
    metadata:
      labels:
        app: ticket-tool-api
    spec:
      containers:
        - name: ticket-tool-api
          image: rafael712/ticket-tool-api:latest
          ports:
            - containerPort: 3333
          env:
            - name: TZ
              value: UTC
            - name: PORT
              value: "3333"
            - name: HOST
              value: 0.0.0.0
            - name: LOG_LEVEL
              value: info
            - name: APP_KEY
              value: 9JmxzSUY8d1HVlANX3MHnEiMGf884d7T
            - name: NODE_ENV
              value: production
            - name: LOG_DRIVER
              value: console
            - name: DB_HOST
              value: mysql-service
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: ticketuser
            - name: DB_PASSWORD
              value: ticketpass
            - name: DB_DATABASE
              value: ticket_tool_db
            - name: SMTP_HOST
              value: sandbox.smtp.mailtrap.io
            - name: SMTP_PORT
              value: "2525"
            - name: SMTP_USERNAME
              value: 703d6c6d38392a
            - name: SMTP_PASSWORD
              value: 0c48f55f264d85

---
apiVersion: v1
kind: Service
metadata:
  name: ticket-tool-api-service
spec:
  selector:
    app: ticket-tool-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3333
  type: ClusterIP

# ===============================
# Job para rodar as migrations do AdonisJS
# ===============================
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ticket-tool-migrations
spec:
  template:
    spec:
      containers:
        - name: migration
          image: rafael712/ticket-tool-api:latest
          command: ["node", "build/ace", "migration:run", "--force"]
          env:
            - name: TZ
              value: UTC
            - name: PORT
              value: "3333"
            - name: HOST
              value: 0.0.0.0
            - name: LOG_LEVEL
              value: info
            - name: APP_KEY
              value: 9JmxzSUY8d1HVlANX3MHnEiMGf884d7T
            - name: NODE_ENV
              value: production
            - name: LOG_DRIVER
              value: console
            - name: DB_HOST
              value: mysql-service
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: ticketuser
            - name: DB_PASSWORD
              value: ticketpass
            - name: DB_DATABASE
              value: ticket_tool_db
            - name: SMTP_HOST
              value: sandbox.smtp.mailtrap.io
            - name: SMTP_PORT
              value: "2525"
            - name: SMTP_USERNAME
              value: 703d6c6d38392a
            - name: SMTP_PASSWORD
              value: 0c48f55f264d85
      restartPolicy: OnFailure
